name: Build & Deploy

on:
  - push
  - pull_request

jobs:
  build_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: pipenv
    - name: Install Python dependencies
      run: |
        curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python3
        pipenv install
    - name: Build
      run: pipenv run mkdocs build -v
    - name: Deploy to Azure
      if: ${{ github.event_name == 'push' }}
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        action: upload
        app_location: site
        skip_app_build: true
        config_file_location: .
    - name: Submit Sitemap
      uses: atymic/sitemap-ping-action@master
      with:
        sitemap-url: https://cpu.ruc.men.ci/sitemap.xml
